version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    networks:
      - web-server_network

  worker:
    build:
      context: ./worker
    command: celery -A tasks worker --loglevel=info
    volumes:
      - ./worker:/app
    depends_on:
      - redis
    networks:
      - web-server_network
  
  tasks:
    build:
      context: ./worker
    command: python app.py
    ports:
      - "5004:5004"
    volumes:
      - ./worker:/app
    depends_on:
      - redis
    networks:
      - web-server_network

networks:
  network:
    driver: bridge
