version: '3'

services:

  nginx:
    image: nginx:latest
    ports:
      - "5050:5050"
    volumes:
        - ./api-gateway/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - network

  app:
    build:
      context: ./app
    command: python app.py
    ports:
      - "5002:5002"
    volumes:
      - ./app:/app
    networks:
      - network

networks:
  network:
    driver: bridge
